### ISSUE TITLE
AEM is not running after finishing provisioning

### ISSUE THREAD

**Issue by Carnifrex** [shinesolutions/puppet-aem-curator#115]
AEM is stopped for deleting the healthcheck content zipfile from the install folder, but previously this was only when setup_repository_volume was true.

Since this commit: https://github.com/shinesolutions/puppet-aem-curator/commit/b5d0a02a441aae5b8954625d326d27d795cdc98f#diff-e4cd4c2ba752ab35edbcece1e746a6ac this also happens when setup_repository_volume = false.

This causes a regression for us: We now no longer have a running instance after provisioning.
Shouldn't AEM be running after running the provisioning steps for installing AEM?

**Comment by Carnifrex** [comment]
Proposed fix: https://github.com/shinesolutions/puppet-aem-curator/pull/116

**Comment by cliffano** [comment]
Hi @Carnifrex ,

There are two phases of provisioning from puppet-aem-curator's point of view.

1. Installation of AEM, which ends up with AEM being gracefully stopped in order to ensure the correctness of the repository.

Because a single AEM installation takes a long time, the desire is to take a machine image of this AEM installation, so we don't have to reinstall AEM every time there is a new AEM environment.
This AEM installation will be used across multiple environments.

This installation is taken care in:
- install_author https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/install_author.pp
- install_publish https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/install_publish.pp

This installation is only needed once for each AEM / service pack / cumulative fix version for a given machine image.

2. Configuration and running of AEM, which ends up with AEM being provisioned with environment-specific details (e.g. an admin password that is unique to that environment, a configuration file that uses the ip address of the server, etc). The idea here is that we can stand up dozens of AEM environments without re-installing AEM itself. It simply uses the machine image taken on step 1.

This configuration is taken care in:
- config_author_primary https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_author_primary.pp
- config_author_standby https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_author_standby.pp
- config_publish https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_publish.pp

This configuration and ensuring that AEM is running is done for each environment stand up.

Hope the above paints a clearer picture. My apologies for not writing this documentation up front on the README.

As for your scenario in particular. I understand that you would like to install AEM and then have it running.
For example: for AEM Author Primary, are you able to call install_author first and then call config_author_primary?
If calling config_* is not an option for you (I understand you might not want the exact same configuration that puppet-aem-curator provides). Would it be possible to just ensure that the aem service is running on your side of the fence, right after calling install_* ?

Looking forward to hear your take on this.

**Comment by Carnifrex** [comment]
Hey @cliffano , thank you for your reply. By using the install and config files you proposed, I now have a working setup that runs after begin configured. Perhaps this reply can serve as a basis for the README file? ;)

**Comment by cliffano** [comment]
Thanks for reminding me @Carnifrex .
I've added the info to README https://github.com/shinesolutions/puppet-aem-curator/blob/master/README.md .

I'll close this ticket, but please feel free to ask if you have further questions.
