### ISSUE TITLE
install_aem_package has force=>true by default, should be changed to force=>false by default

### ISSUE THREAD

**Issue by henrykuijpers** [shinesolutions/puppet-aem-curator#130]
By default, install_aem_package has force=>true. This should be changed to force=>false, as this is default AEM behavior as well.

Furthermore, checks should be in place to see if a package is already installed in the AEM environment, before attempting to even install a package.

force=>true could be specified in the cases where for example SNAPSHOT versions need to be uploaded (and then updated with the newest content).

**Comment by cliffano** [comment]
Done. Thanks for starting the discussion on this one @henrykuijpers  .
Published in 2.6.0 .

For the record, the force value was set to true in order to support early user which use the maven SNAPSHOT build model where multiple changes end up with the same version name. This is no longer be the case, and our preference is for those users to explicitly set force to true.
The default is now back to force is false, consistent with default AEM behaviour.
