### ISSUE TITLE
Reconfiguring aem will uninstall the healthchecks

### ISSUE THREAD

**Issue by Carnifrex** [shinesolutions/puppet-aem-curator#172]
When enabling the reconfig variable on the config step (e.g. config_author_primary or config_publish) the healthchecks will be uninstalled. This wil make sure the reconfiguration will fail as the healtchecks are not there.

Why is there a reconfig boolean in the config step? Is it not the point to reconfigure each time we run a config(e.g. config_author_primary or config_publish)?

**Comment by mbloch1986** [comment]
Hi @Carnifrex do you mind giving me us a little bit more context about your question. Do you have any code line you can refer to ?

I'm going through the reconfiguration process atm and don't understant in which scenario you will end up without installed healthcheck.

Are you referring to these lines ?
https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/reconfig_aem.pp#L121-L142

**Comment by Carnifrex** [comment]
Hey @mbloch1986 I was refering to these lines:
https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_author_primary.pp#L236-L263 and https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_publish.pp#L229-L256

Apparently when running the install and config immediately after eachother, it will leave the healthchecks uninstalled.. Running the config again after this sequence will fix it. I will further investige and update this issue if I find more info.

**Comment by Carnifrex** [comment]
Hey @mbloch1986 

While configuring our environments and executing steps in the [config_author_primary ](https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_author_primary.pp#L236-L263), the config step will remove the healthchecks from AEM. Afterwards, "aem_curator::install_aem_healthcheck" is triggered, this will upload the package but leave the healthcheck package uninstalled.

Do you have any idea why the package will remain uninstalled? Should we perhaps use 'installed' in the [install_aem_healthcheck.pp ](https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/install_aem_healthcheck.pp#L21)?

**Comment by Carnifrex** [comment]
Running the config step on a running environment will not trigger this issue. 

When I start the config step on a stopped environment

**Comment by mbloch1986** [comment]
> Afterwards, "aem_curator::install_aem_healthcheck" is triggered, this will upload the package but leave the healthcheck package uninstalled.

Thanks for the great explenation and your debugging! I see what you mean. Is this on a running AEM instance or is the AEM Service stopped and the start get triggered by the configuration manifest ?

I am experience the same issue, while sometimes I do see an error message in AEM which I have described here 
https://github.com/shinesolutions/puppet-aem-curator/issues/145

I do see this issue sometimes as well and so far I was successfully able to workaround this issue by increasing the `post_start_sleep_seconds` parameter to ~6 mins. Obviously the valu varies depending on the AEM environment.

**Comment by mbloch1986** [comment]
I personally believe this might be an issue with AEM. 

1. We are cleaning the `install` dir while AEM is stopped

https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_author_primary.pp#L249-L251

2. Then we are starting AEM... AEM uninstalls everything which was in the `install` dir and than we are installing the healthcheck and are sleeping around the same time.

3. Post sleep
https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_author_primary.pp#L217-L218

3. AEM Healthcheck package installation
https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_author_primary.pp#L262-L267


Ideally the AEM Healthcheck package installation happens after the post sleep timer. Maybe in your case it happens before the post sleep timer and after triggering the start of the AEM service ? The best would probably to update the manifest to install the healthcheck after the post sleep timer. But this would require to make the post_sleep mandatory instead of an enable flag.

https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/config_author_primary.pp#L214

I hope this helps ?

**Comment by mbloch1986** [comment]
@Carnifrex We'll make the post_sleep_timer mandatory with an upcoming release version. This allows us to make 100% sure the healthcheck package get's installed between the post sleep & checking the login page. 

This change will hopefully fix this issue.

**Comment by mbloch1986** [comment]
@Carnifrex there's actually an issue installing aem packages via the install dir which is described here #145. 

The problem is depending on the file copy mechanism it creates a temporary file in the destination dir which unfortunatley AEM tries to load even though the file copy process hasn't finished yet. 

Therefore copying a file to the AEM Install dir after the startup of AEM is not 100% safe as it may brake the provisoining process sometimes.

**Comment by mbloch1986** [comment]
I'll cose this story, as the root cause for this issue is described in #145.
